# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

[colors]
  [colors.primary]
    background = "#1f1f1f"
    foreground = "#d8dee9"
    dim_foreground = "#a5abb6"

  [colors.cursor]
    text = "#2e3440"
    cursor = "#d8dee9"

  [colors.vi_mode_cursor]
    text = "#2e3440"
    cursor = "#d8dee9"

  [colors.selection]
    text = "CellForeground"
    background = "#4c566a"

  [colors.search.matches]
    foreground = "CellBackground"
    background = "#88c0d0"

  [colors.normal]
    black = "#141515"
    red = "#d63645"
    green = "#a3be8c"
    yellow = "#e6e55c"
    blue = "#66a2de"
    magenta = "#b48ead"
    cyan = "#6fcde8"
    white = "#e5e9f0"

  [colors.bright]
    black = "#4c566a"
    red = "#bf616a"
    green = "#a3be8c"
    yellow = "#ebcb8b"
    blue = "#81a1c1"
    magenta = "#b48ead"
    cyan = "#8fbcbb"
    white = "#eceff4"

  [colors.dim]
    black = "#373e4d"
    red = "#94545d"
    green = "#809575"
    yellow = "#b29e75"
    blue = "#68809a"
    magenta = "#8c738c"
    cyan = "#6d96a5"
    white = "#aeb3bb"


[window]
opacity = 0.96
decorations = "none"

[font.normal]
family = "JetBrains Mono"
